### PR TITLE
feat(Product-page-and-search): implemented product page and search us…

### PR DESCRIPTION
**Pull request by ShankYadav**
…ing unbxd api

### CODE REVIEW

**Comment by yashwal** [comment]
[API to retrieve all the products from given categories](https://trello.com/c/BLYVozeX/17-api-to-retrieve-all-the-products-from-given-categories)

**Comment by yashwal** [comment]
[API to retrieve product details from database](https://trello.com/c/8k0Re7NP/6-api-to-retrieve-product-details-from-database)

**Comment by yashwal** [comment]
[Skeletal frontend using HTML and CSS](https://trello.com/c/4Mq6Q2VS/5-skeletal-frontend-using-html-and-css)

**Comment by ShankYadav** [comment]
[Complete the implementation of UNBXD search API](https://trello.com/c/kfHdpoQf/8-complete-the-implementation-of-unbxd-search-api)

**Comment by ShankYadav** [comment]
[Create the Product Details Page](https://trello.com/c/aPwbayWF/1-create-the-product-details-page)

**Pull request merged**
